name: first_app
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  google_nav_bar: ^5.0.6
  slidable_button: ^2.0.0
  shared_preferences: ^2.1.0
  sqflite: any
  path: any
  http: ^0.13.5
  shimmer: ^2.0.0
  firebase_core: ^2.11.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.3
  firebase_ui_auth: ^1.2.4
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^5.0.11
  image_picker: ^0.8.7+5
  firebase_storage: ^11.2.0
  cached_network_image: ^3.2.3
  get: ^4.6.5
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
