import 'dart:convert';

// List<Products> productModelFromJson(String str) =>
//     List<Products>.from(json.decode(str).map((x) => Products.fromJson(x)));
List<Products> productModelFromJson(String str) => List<Products>.from(
    json.decode(str)['products'].map((x) => Products.fromJson(x)));

// List<Products> categoryModelFromJson(String str) => List<Products>.from(
//     json.decode(str)['category'].map((x) => Products.fromJson(x)));
// toList(List category) {}

// String productModeltoMap(List<Products> data) =>
//     json.encode(List<dynamic>.from(data.map((x) => x.toJson())));

// class ProductDetails {
//   int? id;
//   String? title;
//   String? description;
//   double? price;
//   double? discountPercentage;
//   String? thumbnail;

//   ProductDetails({
//     this.id,
//     this.title,
//     this.description,
//     this.price,
//     this.discountPercentage,
//     this.thumbnail,
//   });

//   factory ProductDetails.fromJson(Map<String, dynamic> json) => ProductDetails(
//         id: json['id'],
//         title: json['title'],
//         description: json['description'],
//         price: json['price'],
//         discountPercentage: json['discountPercentage'],
//         thumbnail: json['thumbnail'],
//       );

//   Map<String, dynamic> toJson() => {
//         'id': id,
//         'title': title,
//         'description': description,
//         'price': price,
//         'discountPercentage': discountPercentage,
//         'thumbnail': thumbnail,
//       };
// }
class Autogenerated {
  List<Products>? products;
  List<String>? category;

  Autogenerated({this.products, this.category});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['products'] != null) {
      products = <Products>[];
      json['products'].forEach((v) {
        products!.add(new Products.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.products != null) {
      data['products'] = this.products!.map((v) => v.toJson()).toList();
    }

    return data;
  }

  //    List<String> _getCategories(List<Products> products) {
  //   return products.map((product) => product.category).toSet().toList();
  // }
}

class Products {
  int? id;
  String? title;
  String? description;
  int? price;
  double? discountPercentage;
  double? rating;
  int? stock;
  String? brand;
  String? category;
  String? thumbnail;
  List<String>? images;
  late bool isFavorite = false;

  Products({
    this.id,
    this.title,
    this.description,
    this.price,
    this.discountPercentage,
    this.rating,
    this.stock,
    this.brand,
    this.category,
    this.thumbnail,
    this.images,
  });

  Products.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    description = json['description'];
    price = json['price'];
    discountPercentage = json['discountPercentage'];
    rating = json['rating'];

    stock = json['stock'];
    brand = json['brand'];
    category = json['category'];
    thumbnail = json['thumbnail'];
    images = json['images'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    data['description'] = this.description;
    data['price'] = this.price;
    data['discountPercentage'] = this.discountPercentage;
    data['rating'] = this.rating;
    data['stock'] = this.stock;
    data['brand'] = this.brand;
    data['category'] = this.category;
    data['thumbnail'] = this.thumbnail;
    data['images'] = this.images;
    return data;
  }

  where(bool Function(dynamic product) param0) {}
}
